### PR TITLE
update documentation and scripts

### PR DESCRIPTION
**Pull request by coleshaw**
@graft , based on your comment about updating the JavaScript, not sure this is needed. But it didn't seem to me that I needed to re-build the JavaScript in the VM, so putting this PR out there.

Wasn't sure if others have run into this same issue? Might also be a good use case for a staging area that always runs the latest `master` code for each project, so I could verify if it's my local install or not.

### CODE REVIEW

**Comment by coleshaw** [comment]
Ugh sorry for all the formatting in the JSX. I use `prettier.io` to auto-format JSX, will turn that off and re-push (though I highly recommend it for the team!).

**Comment by graft** [comment]
:+1:

**Comment by coleshaw** [comment]
@graft , I don't seem to have write access to this repo to merge PRs (though the other two repos were fine). Are there repo permissions missing for the group you added me to? Thanks!

**Comment by graft** [comment]
Fixed.

**Pull request merged**
