### PR TITLE
Cs extract uploader

### PR DESCRIPTION
**Pull request by coleshaw**
This seems to work for me locally, with the same functionality as before. I can upload files, pause, restart, and cancel them.

### CODE REVIEW

**Comment by corps** [comment]
To fix the failing test, you should change the "test" command in `package.json` to use the bin in `node_modules` dir.

**Comment by coleshaw** [comment]
@graft any feedback on this? I think if we get this merged in we can then also get @corps folder uploader deployed to staging for testing.

**Comment by graft** [comment]
I'm curious about the upload_reducer being "left behind", with a lot of entangling action dispatch expected from 'etna/actions'. Should it stay or should it go?

**Comment by coleshaw** [comment]
> I'm curious about the upload_reducer being "left behind", with a lot of entangling action dispatch expected from 'etna/actions'. Should it stay or should it go?

Thanks, forgot to swap that out for the version in `etna`!

**Comment by corps** [comment]
Moving forward with merging this.  I verified webpack build and npm installs works, app looks good.  Failing test is due to missing data directory initialization in github actions, but I have fix in monorepo already, can verify test passes otherwise.

**Pull request merged**
