### PR TITLE
Metis client

### PR DESCRIPTION
**Pull request by graft**
This completes #67, adding in most of the basic functionality of the metis shell client.

### CODE REVIEW

**Comment by graft** [comment]
I began writing a spec to cover the client's behavior, but there are several complications making the test setup difficult.

1. Tokens - the MetisClient parses the user's tokens to determine the valid list of projects they can access on Metis. This expects the token to be formatted as according to the requirements of Etna::Auth, that is as a valid JWT. When the MetisClient makes a request to Metis it sends this token along with it. We are stubbing requests using WebMock, which has a very nice stubbing `.to_rack(app)` feature. However, the testing application uses Etna::TestAuth, which uses dummy tokens. This dummy token format is different from the actual JWT format (it has 1 base64-encoded value, while JWT has 3 base64-encoded values joined by "."). This creates a conflict in the token format we should pass into the client. We could instead have the testing application use Etna::Auth, but this would require an actual signed token, which seems annoying. We could instead patch Etna::TestAuth so its token format more closely matches Etna::Auth (that is, [ header, payload, signature ].join('.')); in place of this I have left an ugly kludge which checks for the test env.

2. Hmac authentication - a similar error occurs with HMAC-signed routes: the TestAuth layer expects to be told 'invalid' or 'valid' status in a dummy hmac signature, but the client is using real HMAC-signed routes from the app itself.

3. Readline - some of the interactions (mostly around tab completion) are hard to test because they occur inside the Readline library. Even debugging these is hard since most debuggers use Readline themselves. I avoided writing specs for most of this behavior. However, i've observed several crashes related to tab completion, so being able to test this would be nice.

4. Self-editing - the script actually modifies itself, to replace the line `CONFIG_FILE=...` with a new value. I have no idea how to test this monstrosity.

**Comment by coleshaw** [comment]
Just for documentation's sake, when I ran this, it expected a `TOKEN`:

```
developer@ubuntu-vm metis (graft-metis-client $%=) $ ./bin/metis_client
Location for config file? [~/.metis.json]
Cookie name for metis uid? [METIS_UID]
Hostname for metis? [metis.example.org] metis-dev.etna-development.org
Config saved at ~/.metis.json
Traceback (most recent call last):
	3: from ./bin/metis_client:848:in `<main>'
	2: from ./bin/metis_client:844:in `start'
	1: from ./bin/metis_client:844:in `new'
./bin/metis_client:597:in `initialize': No environment variable TOKEN is set (RuntimeError)
```

I needed to add an environment variable with my Janus token. To do this, I went to the appropriate Janus URL, clicked "Copy Token", and then in my shell did `$ export TOKEN=<paste>`.

**Comment by coleshaw** [comment]
Looks good to me, `get` and `put` seem to work.

**Comment by arkal** [comment]
Highly recommend some help text if the user provides no arguments or if the arguments include `-h` or `--help`.

**Comment by arkal** [comment]
Found an error. Attempting to use tab completion in the client crashed it.

```
[arrao@cclc01 bin]$ ./metis_client 
> project mvir1
mvir1:> ls daTraceback (most recent call last):
	8: from ./metis_client:848:in `<main>'
	7: from ./metis_client:844:in `start'
	6: from ./metis_client:708:in `run'
	5: from ./metis_client:708:in `readline'
	4: from ./metis_client:681:in `block in run'
	3: from ./metis_client:659:in `complete'
	2: from ./metis_client:166:in `list_folder'
	1: from /home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/common.rb:104:in `escape'
/home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/rfc2396_parser.rb:305:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError)
```

**Comment by arkal** [comment]
Also, is there any way to script using the client? With `metis_put` i could write a script to do
```
metis_put /tmp/arrao/foo metis://metis.ucsf.edu/mvir1/data/
```
but that won't work now
```
/krummellab/data1/arrao/software/metis/bin/metis_client put /tmp/arrao/foo metis://metis.ucsf.edu/mvir1/data/
Invalid command. Try:
mv	ls	project	cd	get	put
```

**Comment by arkal** [comment]
suggest adding a `source` or `extern` command that lets you run commands from an external script so the user can batch run a bunch of uploads

**Comment by arkal** [comment]
I think better behavior for `put` would be something like
```
    def run(*input_files)
      if input_files.length() > 1 && x[2] =~ /^remotes:\/\//
        # Last argument was of the form remotes://<PROJECT>/<PATH/TO/DESIRED/FOLDER>
        @shell.project_name=<PROJECT>
        @shell.cwd=<PATH/TO/DESIRED/FOLDER>
        # Remove the last item from the array
        input_files.pop
      end

      raise ShellError, 'No remote folder selected!' unless @shell.cwd

      raise ShellError, 'No input files selected!' if input_files.empty?

      # get a listing of the folder
      folder = @shell.client.list_folder(@shell.project_name, @shell.cwd)

      input_files.each do |file_or_folder|
        upload(file_or_folder, @shell.cwd, folder)
      end
    end
```

so the default is to drop everything into cwd but the user can provide a desired output. This way if i want to put 3 folders in 3 different locations, i don't have to to
```
cd loc1
put folder1
cd loc2
put folder2
cd loc3
put folder3
```

**Comment by arkal** [comment]
suggest adding `pwd`

**Comment by arkal** [comment]
Found an error. Cannot cd up the tree to the root level of a project with `..`
```
[arrao@cclc01 projects]$ /krummellab/data1/arrao/software/metis/bin/metis_client 
> project mvir
No such project 'mvir'. Try:
ipi	mvir1	xcan1	xvir1
> project mvir1
mvir1:> cd data/single_cell_GEX
mvir1:data/single_cell_GEX> cd ..
mvir1:data> cd ..
Traceback (most recent call last):
	7: from /krummellab/data1/arrao/software/metis/bin/metis_client:848:in `<main>'
	6: from /krummellab/data1/arrao/software/metis/bin/metis_client:844:in `start'
	5: from /krummellab/data1/arrao/software/metis/bin/metis_client:709:in `run'
	4: from /krummellab/data1/arrao/software/metis/bin/metis_client:745:in `run_command'
	3: from /krummellab/data1/arrao/software/metis/bin/metis_client:416:in `run'
	2: from /krummellab/data1/arrao/software/metis/bin/metis_client:166:in `list_folder'
	1: from /home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/common.rb:104:in `escape'
/home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/rfc2396_parser.rb:305:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError)
[arrao@cclc01 projects]$ 
```

Also, 
```
[arrao@cclc01 projects]$ /krummellab/data1/arrao/software/metis/bin/metis_client 
> project mvir1
mvir1:> cd data/single_cell_GEX
mvir1:data/single_cell_GEX> cd ../
mvir1:data> cd single_cell_GEX
mvir1:data/single_cell_GEX> cd ../../
Traceback (most recent call last):
	7: from /krummellab/data1/arrao/software/metis/bin/metis_client:848:in `<main>'
	6: from /krummellab/data1/arrao/software/metis/bin/metis_client:844:in `start'
	5: from /krummellab/data1/arrao/software/metis/bin/metis_client:709:in `run'
	4: from /krummellab/data1/arrao/software/metis/bin/metis_client:745:in `run_command'
	3: from /krummellab/data1/arrao/software/metis/bin/metis_client:416:in `run'
	2: from /krummellab/data1/arrao/software/metis/bin/metis_client:166:in `list_folder'
	1: from /home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/common.rb:104:in `escape'
/home/arrao/.rbenv/versions/2.5.7/lib/ruby/2.5.0/uri/rfc2396_parser.rb:305:in `escape': undefined method `gsub' for nil:NilClass (NoMethodError)
```

**Comment by arkal** [comment]
`cd` can't handle absolute paths

**Comment by graft** [comment]
The command syntax is like: `metis_client <metis_path> <command>`, where `<metis_path>` is like `metis://<project_name>/<folder_path>`; it will basically set `@shell.cwd` to be whatever the metis path is, then run the command. This should let you batch whatever you want.

As for having a metis path argument to put, I think I prefer the simpler syntax; in combination with the above I think it should be sufficient (that is, you'd usually want to do multiple puts in command mode anyway).

I'll add `pwd` and `lcd` and sort out some of these cd issues.

**Comment by arkal** [comment]
I see your point about the "simpler syntax" but I also feel like choosing a new syntax that is different from the conventional cp/mv/scp/is unnecessary. It requires your user to mentally have to switch to your custom, enforced, syntax.

```
# analogous to scp <local_filedir1> [<local_filedirn>] <remote_path>
metis_client put <local_filedir1> [<local_filedirn>] folded <metis_path>
# analogous to scp <remote_path1> [<remote_pathn>] <local_path>
metis_client get <metis_path1> [<metis_pathn>] <local_path>
# analogous to ls. Also allows multiple dirs from the same or different projects to be printed (useful for multi-project alliances)
metis_client ls <metis_path1> [<metis_pathn>]
# analogous to mv.
metis_client mv <metis_path1> [<metis_pathn>] <metis_path>
```

**Comment by graft** [comment]
I may have changed my mind overnight about the value of specifying a destination. I'm not sure I like the remote: syntax, however, since it breaks the shell-like feel of the interface. It is more natural to just say `put <local directory> <remote directory>`, which is the same behavior `cd`, `ls`, etc., have. The value of the remote: syntax (actually I would use the metis path, `metis://<path>`) is it allows you to have both an aribtrary number of inputs and an optional remote directory (so you could do `put localdir1 localdir2` and `put localdir1 localdir2 metis://remotedir`); in the absence of the metis path you'd have to choose between one or the other, i.e., either you allow multiple inputs and require a remote path as the final argument, or you only allow a single input with an optional remote dir.

Of the three (use remotes, allow multiple inputs, allow optional target) I think I favor the last, which is the behavior of lftp's `mirror`, i.e., `mirror <source> [ <target> ]`

As for better behavior for ls, etc., I agree, but I feel that's out of scope here, I just want to get an initial build up in place and we can workshop the commands later if necessary. This might all become obsolete very quickly if we can get #46 working.

**Comment by arkal** [comment]
I'm fine with `metis://` rather than `remote://`. Since this format is just for CLI i think it makes more sense to have `metis://`. I figured `metis://` was moot since we're already on metis hence the generic term `remote://` as a placeholder.

```
in the absence of the metis path you'd have to choose between one or the other, i.e., either you allow multiple inputs and require a remote path as the final argument, or you only allow a single input with an optional remote dir.```

I don't see why the last argument can't always be the destination....... If you want it to go to CWD, use `.` as you would with cp, ls, mv. 

Yes your idea mirrors (pun intended) lftp's `mirror` and i HATE that because it's counterintuitive to what one would normally do.

**Comment by graft** [comment]
Ok fair. I'll make it `put <input files> <remote_dir>` - I don't know if `.` is supported, so I'll validate that as well.

**Comment by arkal** [comment]
SGTM!

**Comment by arkal** [comment]
You shouldn't be checking for TOKEN in ENV till the user attempts to run an actual command. Running `./metis-client` and your choice of any to all of `./metis-client -h`, ``./metis-client --help` , or `./metis-client help` should print a help message that explains what the token is and how to set it up.
```
[arrao@cclc01 bin]$ ./metis_client 
Traceback (most recent call last):
	3: from ./metis_client:883:in `<main>'
	2: from ./metis_client:879:in `start'
	1: from ./metis_client:879:in `new'
./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
[arrao@cclc01 bin]$ ./metis_client --help
Traceback (most recent call last):
	3: from ./metis_client:883:in `<main>'
	2: from ./metis_client:879:in `start'
	1: from ./metis_client:879:in `new'
./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
[arrao@cclc01 bin]$ ./metis_client -h
Traceback (most recent call last):
	3: from ./metis_client:883:in `<main>'
	2: from ./metis_client:879:in `start'
	1: from ./metis_client:879:in `new'
./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
```

Since `./metis_client` actually puts you into the shell, i propose using something like `./metis_client shell` for interactive mode else it's CLI? Too much?

**Comment by arkal** [comment]
Help text for lcd is a copy of cd and is misleading.
```
> help pwd
Usage:
pwd
> help lcd
Usage:
cd [<remote_folder_path>]
```

**Comment by arkal** [comment]
`pwd` prints directory on local machine and not the metis url.

**Comment by arkal** [comment]
Would be nice if cd could understand metis paths and set project accordingly. Not a dealbreaker though. Maybe a future feature.
```
> cd metis://mvir1/data
No such folder metis://mvir1/data
> project mvir1
mvir1:> cd data
mvir1:data> 
```

**Comment by arkal** [comment]
Would be nice to have a `projects` command that lists authorized projects. Not a dealbreaker. For the future

**Comment by arkal** [comment]
> You shouldn't be checking for TOKEN in ENV till the user attempts to run an actual command. Running `./metis-client` and your choice of any to all of `./metis-client -h`, ``./metis-client --help`, or`./metis-client help` should print a help message that explains what the token is and how to set it up. Else there's no way of knowing that it is possible to use metis_client in non-interactive scripting mode.
> 
> ```
> [arrao@cclc01 bin]$ ./metis_client 
> Traceback (most recent call last):
> 	3: from ./metis_client:883:in `<main>'
> 	2: from ./metis_client:879:in `start'
> 	1: from ./metis_client:879:in `new'
> ./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
> [arrao@cclc01 bin]$ ./metis_client --help
> Traceback (most recent call last):
> 	3: from ./metis_client:883:in `<main>'
> 	2: from ./metis_client:879:in `start'
> 	1: from ./metis_client:879:in `new'
> ./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
> [arrao@cclc01 bin]$ ./metis_client -h
> Traceback (most recent call last):
> 	3: from ./metis_client:883:in `<main>'
> 	2: from ./metis_client:879:in `start'
> 	1: from ./metis_client:879:in `new'
> ./metis_client:621:in `initialize': No environment variable TOKEN is set (RuntimeError)
> ```
> 
> Since `./metis_client` actually puts you into the shell, i propose using something like `./metis_client shell` for interactive mode else it's CLI? Too much?

On second thought, i think `./metis_client -i/--interactive` should put you into the shell and `./metis_client -p/--project <project>` should automatically set the project. So the syntax for running an ls would be
```
./metis_client -p mvir1 ls
# instead of 
./metis_client metis://mvir1 ls
```

**Comment by coleshaw** [comment]
@arkal , for the proposed `projects` command, could you elaborate what behavior you would expect, different from the existing `project` command? I get a list of what I assume to be my authorized projects with `project`:

```
> project
No such project. Try:
ipi
```

**Comment by arkal** [comment]
Good point. I tried `project foo` and i got the same prompt you did. I should have made the connection that `project` with no arguments would give the same thing. I guess maybe aesthetically, It would be nice for project without a username to not be an error.
```
>project
Available projects for your username are
mvir1 test2 ipi3
>project foo
Error: No such project
Available projects for your username are
mvir1 test2 ipi3
```

**Comment by graft** [comment]
Fixed the lcd docs and made the TOKEN error message a little better. The other points are all good but I'd like to merge this much at this point, we can improve from here.

**Pull request merged**
